"""v2

Revision ID: 17277c625055
Revises: c36997241853
Create Date: 2026-05-27 05:58:01.216125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17277c625055'
down_revision: Union[str, None] = 'c36997241853'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('llm_provider', sa.String(length=50), nullable=False),
    sa.Column('llm_api_key', sa.Text(), nullable=False),
    sa.Column('llm_base_url', sa.Text(), nullable=False),
    sa.Column('llm_model_name', sa.String(length=255), nullable=False),
    sa.Column('llm_temperature', sa.Float(), nullable=False),
    sa.Column('llm_max_retries', sa.Integer(), nullable=False),
    sa.Column('github_token', sa.Text(), nullable=False),
    sa.Column('github_repo', sa.String(length=500), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.add_column('users', sa.Column('oauth_provider', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('oauth_subject', sa.String(length=255), nullable=True))
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.create_unique_constraint('uq_users_oauth_identity', 'users', ['oauth_provider', 'oauth_subject'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_users_oauth_identity', 'users', type_='unique')
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.drop_column('users', 'oauth_subject')
    op.drop_column('users', 'oauth_provider')
    op.drop_table('user_settings')
    # ### end Alembic commands ###
