"""v3

Revision ID: 26f645063c9a
Revises: 17277c625055
Create Date: 2026-05-27 23:54:45.743202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26f645063c9a'
down_revision: Union[str, None] = '17277c625055'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_settings', sa.Column('llm_api_key_encrypted', sa.Text(), nullable=False))
    op.add_column('user_settings', sa.Column('github_token_encrypted', sa.Text(), nullable=False))
    op.add_column('user_settings', sa.Column('github_use_oauth', sa.Boolean(), nullable=False))
    op.add_column('user_settings', sa.Column('terraform_token_encrypted', sa.Text(), nullable=False))
    op.add_column('user_settings', sa.Column('terraform_workspace', sa.String(length=255), nullable=False))
    op.drop_column('user_settings', 'llm_api_key')
    op.drop_column('user_settings', 'github_token')
    op.add_column('users', sa.Column('oauth_access_token_encrypted', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'oauth_access_token_encrypted')
    op.add_column('user_settings', sa.Column('github_token', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('user_settings', sa.Column('llm_api_key', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('user_settings', 'terraform_workspace')
    op.drop_column('user_settings', 'terraform_token_encrypted')
    op.drop_column('user_settings', 'github_use_oauth')
    op.drop_column('user_settings', 'github_token_encrypted')
    op.drop_column('user_settings', 'llm_api_key_encrypted')
    # ### end Alembic commands ###
